# Generated by Django 5.0.4 on 2024-04-23 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hm_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='desc',
        ),
    ]
