# Generated by Django 5.0.4 on 2024-04-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('activity_years', models.IntegerField()),
                ('last_song', models.CharField(max_length=50)),
                ('popular_song', models.CharField(max_length=50)),
                ('twitter_username', models.CharField(blank=True, max_length=50, null=True)),
                ('youtube_channel_id', models.CharField(blank=True, max_length=50, null=True)),
                ('soundcloud_username', models.CharField(blank=True, max_length=50, null=True)),
                ('niconico_user_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='accessrecord',
            name='webname',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='topic',
        ),
        migrations.DeleteModel(
            name='UwUTeam',
        ),
        migrations.DeleteModel(
            name='AccessRecord',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='WebPage',
        ),
    ]
