# Generated by Django 5.0.4 on 2024-04-23 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hm_app', '0002_remove_producer_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='soundcloud_username',
        ),
    ]
