# Generated by Django 5.0.4 on 2024-04-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_app', '0004_producer_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='youtube_channel_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
