# Generated by Django 5.0.4 on 2024-04-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_app', '0005_alter_producer_youtube_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='picture_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='youtube_channel_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
